apiVersion: v1
kind: Namespace
metadata:
  name: docs
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: docs
spec:
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      docs:
        - name: docs
          image: ghcr.io/quasarch/quasarch-docs
          ports:
            - name: api
              containerPort: 1313
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: docs
spec:
  selector:
    app: docs
  type: ClusterIP
  ports:
    - name: docs
      port: 1313
      targetPort: docs

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  name: docs
  namespace: docs
spec:
  ingressClassName: nginx
  rules:
    - host: docs.quasarch.cloud
    http:
      paths:
        - backend:
          service:
            name: docs
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - docs.quasarch.cloud
    secretName: docs-cert